### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by SimonFurtm** [SimonFurtm/CO2-TemperaturProjekt#3]
Hauptziele des Epic:
- [ ] Die Daten der Sensoren sollen dargestellt werden können. 
- [ ] Die Visualisierung der Daten soll auf sämtlichen Betriebssystemen und Endgeräten möglich sein.  
- [ ] Website ist per Webserver aufrufbar

Teilziele:
- [ ] Daten werden auf der Website dargestellt (z.B. siehe Zielbestimmung zu Website)
- [ ] Daten können auf mehreren Geräten angezeigt werden (responsive)
- [ ] Benutzer können Grenzwert für CO2, Temperatur und Luftfeuchtigkeit einstellen
- [ ] Benutzer werden über E-Mail benachrichtigt, wenn ein Grenzwert überschritten wird
- [ ] Webserver ist aufrufbar
