### ISSUE TITLE
Datenspeicherung

### ISSUE THREAD

**Issue by SimonFurtm** [SimonFurtm/CO2-TemperaturProjekt#4]
Hauptziele:
- [ ] Die Daten der Sensoren sollen dauerhaft gespeichert werden können
- [ ] Die aufgezeichneten Daten sollen auch anderen Applikationen zur Verfügung gestellt werden können 

Teilziele:
- [ ] Daten können über (z.B JSON), Dateien ausgelesen werden
- [ ] Datenbank wurde aufgesetzt
- [ ] Daten werden von den Sensoren in die Datenbank geschickt 
- [ ] Daten werden von den Sensoren in die Datenbank geschickt 
- [ ] Datenbankserver ist aufrufbar
