### ISSUE TITLE
Messwerte

### ISSUE THREAD

**Issue by SimonFurtm** [SimonFurtm/CO2-TemperaturProjekt#5]
Hauptziele:
- [ ] Es sollen beliebig viele Sensoren im System angelegt werden können
- [ ] Für jeden Sensor soll ein Grenzwert definiert werden können

Nebenziele:
- [ ] RPI Skript das uns die Daten liefert
- [ ] Benutzer können neue Sensoren im System anhängen
